version: '3'

volumes:
  database_local:

services:
  DjangoBlog_lcoal:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: DjangoBlog_local
    working_dir: /app
    volumes:
      - database_local:/app/database
      - .:/app
    ports:
      - "8000:8000"
    command: /start.sh