version: '3'

volumes:
  static:
  database:

services:
  DjangoBlog；
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: LearingDjango
    container_name: LearingDjango
    working_dir: /app
    volumes:
      - database:/app/database
      - static:/app/static
    env_file:
      - .envs/.production
    ports:
      - "8000:8000"
    command: /start.sh

  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: LearingDjango_nginx
    container_name: LearningDjango_nginx
    volumes:
      - static:/app/LearingDjango/static
    ports:
      - "80:80"
      - "443:443"
