"""
Django settings for PersonalBlog project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from .common import *
# __name__ == "__main__"
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/
ALLOWED_HOSTS = ['*']
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'z5auurqj&01&@nqw!a&z!uu@1g8*i-(i&5w!b_5k^%$&4am8h3'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

HAYSTACK_CONNECTIONS['default']['URL'] = 'http://elasticsearch_local:9200/'



